/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as InstructorRouteImport } from './routes/_instructor'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as StudentStudentModulesRouteImport } from './routes/_student/student/modules'
import { Route as StudentStudentKycRouteImport } from './routes/_student/student/kyc'
import { Route as StudentStudentDashboardRouteImport } from './routes/_student/student/dashboard'
import { Route as StudentStudentAssignmentsRouteImport } from './routes/_student/student/assignments'
import { Route as InstructorInstructorSubmissionsRouteImport } from './routes/_instructor/instructor/submissions'
import { Route as InstructorInstructorModulesRouteImport } from './routes/_instructor/instructor/modules'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AdminAdminKycRouteImport } from './routes/_admin/admin/kyc'
import { Route as AdminAdminInstructorModulesRouteImport } from './routes/_admin/admin/instructor-modules'
import { Route as StudentStudentLessonsIdRouteImport } from './routes/_student/student/lessons/$id'
import { Route as InstructorInstructorModulesModuleIdRouteImport } from './routes/_instructor/instructor/modules/$moduleId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/_instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentModulesRoute = StudentStudentModulesRouteImport.update({
  id: '/student/modules',
  path: '/student/modules',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentKycRoute = StudentStudentKycRouteImport.update({
  id: '/student/kyc',
  path: '/student/kyc',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentDashboardRoute = StudentStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentAssignmentsRoute =
  StudentStudentAssignmentsRouteImport.update({
    id: '/student/assignments',
    path: '/student/assignments',
    getParentRoute: () => StudentRoute,
  } as any)
const InstructorInstructorSubmissionsRoute =
  InstructorInstructorSubmissionsRouteImport.update({
    id: '/instructor/submissions',
    path: '/instructor/submissions',
    getParentRoute: () => InstructorRoute,
  } as any)
const InstructorInstructorModulesRoute =
  InstructorInstructorModulesRouteImport.update({
    id: '/instructor/modules',
    path: '/instructor/modules',
    getParentRoute: () => InstructorRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminKycRoute = AdminAdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminInstructorModulesRoute =
  AdminAdminInstructorModulesRouteImport.update({
    id: '/admin/instructor-modules',
    path: '/admin/instructor-modules',
    getParentRoute: () => AdminRoute,
  } as any)
const StudentStudentLessonsIdRoute = StudentStudentLessonsIdRouteImport.update({
  id: '/student/lessons/$id',
  path: '/student/lessons/$id',
  getParentRoute: () => StudentRoute,
} as any)
const InstructorInstructorModulesModuleIdRoute =
  InstructorInstructorModulesModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => InstructorInstructorModulesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin/instructor-modules': typeof AdminAdminInstructorModulesRoute
  '/admin/kyc': typeof AdminAdminKycRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/instructor/modules': typeof InstructorInstructorModulesRouteWithChildren
  '/instructor/submissions': typeof InstructorInstructorSubmissionsRoute
  '/student/assignments': typeof StudentStudentAssignmentsRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/kyc': typeof StudentStudentKycRoute
  '/student/modules': typeof StudentStudentModulesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/instructor/modules/$moduleId': typeof InstructorInstructorModulesModuleIdRoute
  '/student/lessons/$id': typeof StudentStudentLessonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin/instructor-modules': typeof AdminAdminInstructorModulesRoute
  '/admin/kyc': typeof AdminAdminKycRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/instructor/modules': typeof InstructorInstructorModulesRouteWithChildren
  '/instructor/submissions': typeof InstructorInstructorSubmissionsRoute
  '/student/assignments': typeof StudentStudentAssignmentsRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/kyc': typeof StudentStudentKycRoute
  '/student/modules': typeof StudentStudentModulesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/instructor/modules/$moduleId': typeof InstructorInstructorModulesModuleIdRoute
  '/student/lessons/$id': typeof StudentStudentLessonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_instructor': typeof InstructorRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_admin/admin/instructor-modules': typeof AdminAdminInstructorModulesRoute
  '/_admin/admin/kyc': typeof AdminAdminKycRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_instructor/instructor/modules': typeof InstructorInstructorModulesRouteWithChildren
  '/_instructor/instructor/submissions': typeof InstructorInstructorSubmissionsRoute
  '/_student/student/assignments': typeof StudentStudentAssignmentsRoute
  '/_student/student/dashboard': typeof StudentStudentDashboardRoute
  '/_student/student/kyc': typeof StudentStudentKycRoute
  '/_student/student/modules': typeof StudentStudentModulesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_instructor/instructor/modules/$moduleId': typeof InstructorInstructorModulesModuleIdRoute
  '/_student/student/lessons/$id': typeof StudentStudentLessonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/admin/instructor-modules'
    | '/admin/kyc'
    | '/admin/users'
    | '/instructor/modules'
    | '/instructor/submissions'
    | '/student/assignments'
    | '/student/dashboard'
    | '/student/kyc'
    | '/student/modules'
    | '/api/auth/$'
    | '/instructor/modules/$moduleId'
    | '/student/lessons/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/admin/instructor-modules'
    | '/admin/kyc'
    | '/admin/users'
    | '/instructor/modules'
    | '/instructor/submissions'
    | '/student/assignments'
    | '/student/dashboard'
    | '/student/kyc'
    | '/student/modules'
    | '/api/auth/$'
    | '/instructor/modules/$moduleId'
    | '/student/lessons/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_instructor'
    | '/_student'
    | '/dashboard'
    | '/onboarding'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_admin/admin/instructor-modules'
    | '/_admin/admin/kyc'
    | '/_admin/admin/users'
    | '/_instructor/instructor/modules'
    | '/_instructor/instructor/submissions'
    | '/_student/student/assignments'
    | '/_student/student/dashboard'
    | '/_student/student/kyc'
    | '/_student/student/modules'
    | '/api/auth/$'
    | '/_instructor/instructor/modules/$moduleId'
    | '/_student/student/lessons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InstructorRoute: typeof InstructorRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_instructor': {
      id: '/_instructor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/student/modules': {
      id: '/_student/student/modules'
      path: '/student/modules'
      fullPath: '/student/modules'
      preLoaderRoute: typeof StudentStudentModulesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/kyc': {
      id: '/_student/student/kyc'
      path: '/student/kyc'
      fullPath: '/student/kyc'
      preLoaderRoute: typeof StudentStudentKycRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/dashboard': {
      id: '/_student/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentStudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/assignments': {
      id: '/_student/student/assignments'
      path: '/student/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentStudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_instructor/instructor/submissions': {
      id: '/_instructor/instructor/submissions'
      path: '/instructor/submissions'
      fullPath: '/instructor/submissions'
      preLoaderRoute: typeof InstructorInstructorSubmissionsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_instructor/instructor/modules': {
      id: '/_instructor/instructor/modules'
      path: '/instructor/modules'
      fullPath: '/instructor/modules'
      preLoaderRoute: typeof InstructorInstructorModulesRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/kyc': {
      id: '/_admin/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminAdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/instructor-modules': {
      id: '/_admin/admin/instructor-modules'
      path: '/admin/instructor-modules'
      fullPath: '/admin/instructor-modules'
      preLoaderRoute: typeof AdminAdminInstructorModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/student/lessons/$id': {
      id: '/_student/student/lessons/$id'
      path: '/student/lessons/$id'
      fullPath: '/student/lessons/$id'
      preLoaderRoute: typeof StudentStudentLessonsIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_instructor/instructor/modules/$moduleId': {
      id: '/_instructor/instructor/modules/$moduleId'
      path: '/$moduleId'
      fullPath: '/instructor/modules/$moduleId'
      preLoaderRoute: typeof InstructorInstructorModulesModuleIdRouteImport
      parentRoute: typeof InstructorInstructorModulesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminInstructorModulesRoute: typeof AdminAdminInstructorModulesRoute
  AdminAdminKycRoute: typeof AdminAdminKycRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminInstructorModulesRoute: AdminAdminInstructorModulesRoute,
  AdminAdminKycRoute: AdminAdminKycRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface InstructorInstructorModulesRouteChildren {
  InstructorInstructorModulesModuleIdRoute: typeof InstructorInstructorModulesModuleIdRoute
}

const InstructorInstructorModulesRouteChildren: InstructorInstructorModulesRouteChildren =
  {
    InstructorInstructorModulesModuleIdRoute:
      InstructorInstructorModulesModuleIdRoute,
  }

const InstructorInstructorModulesRouteWithChildren =
  InstructorInstructorModulesRoute._addFileChildren(
    InstructorInstructorModulesRouteChildren,
  )

interface InstructorRouteChildren {
  InstructorInstructorModulesRoute: typeof InstructorInstructorModulesRouteWithChildren
  InstructorInstructorSubmissionsRoute: typeof InstructorInstructorSubmissionsRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorInstructorModulesRoute:
    InstructorInstructorModulesRouteWithChildren,
  InstructorInstructorSubmissionsRoute: InstructorInstructorSubmissionsRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

interface StudentRouteChildren {
  StudentStudentAssignmentsRoute: typeof StudentStudentAssignmentsRoute
  StudentStudentDashboardRoute: typeof StudentStudentDashboardRoute
  StudentStudentKycRoute: typeof StudentStudentKycRoute
  StudentStudentModulesRoute: typeof StudentStudentModulesRoute
  StudentStudentLessonsIdRoute: typeof StudentStudentLessonsIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentAssignmentsRoute: StudentStudentAssignmentsRoute,
  StudentStudentDashboardRoute: StudentStudentDashboardRoute,
  StudentStudentKycRoute: StudentStudentKycRoute,
  StudentStudentModulesRoute: StudentStudentModulesRoute,
  StudentStudentLessonsIdRoute: StudentStudentLessonsIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InstructorRoute: InstructorRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
